# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_attend_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
